spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:bank_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: test
    drop-first: true

logging:
  level:
    root: WARN
    org.springframework.test: DEBUG
