spring:
  application:
    name: card-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    secret: ${JWT_SECRET:super_secret_key_which_is_at_least_32_chars_long}
    expiration-minutes: 60
